source 'https://rubygems.org'

gem 'rake'
gem 'temple'
gem 'pry'
gem 'minitest'
gem 'minitest-reporters'
gem 'rhaml-parser', github: 'mluts/rhaml-parser', tag: 'v0.1.4'
gem 'micromachine'
gem 'guard'
gem 'guard-minitest'
